version: '3'
services:
  mysql:
    build: ./database
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    container_name: mysql-container
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d